apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aoic-spring-boot
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: aoic-spring-boot
        tier: display
    spec:
      containers:
        - image: ragudiko/aoic-spring-boot
          name: aoic-spring-boot
          #image: gcr.io/Pipelines/nginx:1.7.9
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 8090
