apiVersion: v1
kind: Service
metadata:
  name: aoic-spring-boot
  labels:
    app: aoic-spring-boot
spec:
  type: NodePort
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8080
      nodePort: 30094
  selector:
    app: aoic-spring-boot
    tier: display
